"""Initial ProxyAtlas schema.

The full schema is defined by the SQLAlchemy models. This revision materializes
that metadata so upgrades/downgrades stay in lockstep with the ORM for the
initial release. Subsequent schema changes should be authored as explicit
autogenerated revisions.

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-24
"""
from __future__ import annotations

from alembic import op

from app.database.models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind)
